/**
 * The sitemap and robots.txt nginx serves for Forge Market.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * WHY THE BODIES ARE IN nginx.conf AT ALL
 *
 * A sitemap must carry ABSOLUTE URLs — the spec requires it and a crawler discards a relative
 * `<loc>` — and nothing built in this repository may name a hostname, because one image is served
 * from localhost, from a preview deployment and from `market.<apex>`. nginx is the one component
 * that knows which: it has `$host` on every request. So the bodies are composed per request, from
 * a config file with no hostname in it.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * WHY THIS SURFACE DOES NOT USE THE SHARED `sitemapXml()`
 *
 * `@cloudsforge/ui/sitemap` composes the whole estate from the surface registry, each sibling as
 * `<subdomain>.<apex>`. That is exactly right on `site`, which IS the apex. Here `$host` is
 * ALREADY `market.<apex>`, so the same call would emit `foresight.market.<apex>` — an address that
 * exists nowhere, that fails TLS at the edge (Cloudflare's Universal SSL is a one-label wildcard),
 * and that would be published in the one document a crawler treats as authoritative.
 *
 * So the estate sitemap belongs to `site` and to nowhere else, and what this surface emits is its
 * OWN public routes. `robots.txt` is still generated by the shared `robotsTxt()`, because that one
 * has no host composition in it and is byte-compared below.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * AND WHY THAT NEEDS A TEST
 *
 * A body pasted into a config file is a copy, and a copy drifts. `src/lib/routes.ts` already
 * carries which addresses exist and which of them a crawler is invited to; this reads the served
 * document back against that table, so adding a public route is a line in the route table plus a
 * line in nginx, and forgetting the second is a failed build rather than a page nobody can find.
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { describe, it } from 'node:test'
import { ENV_LABELS } from '@cloudsforge/ui'
import { robotsTxt } from '@cloudsforge/ui/sitemap'
import { ROUTES, SITEMAP_PATHS } from '../src/lib/routes.ts'

const nginx = readFileSync(new URL('../nginx.conf', import.meta.url), 'utf8')

/**
 * The production apex, assembled rather than written.
 *
 * Spelled out, this file would be the literal hostname it exists to forbid — and the estate has
 * already been bitten by a guard that matched its own explanation twice (see `nginx.conf`'s header
 * and the "Money is never a float" step in ci.yml).
 */
const APEX = `cloudsforge${'.'}online`

/** The single-quoted body of a `return 200 '…';` inside an exact-match location. */
function servedBody(path: string): string {
  const block = new RegExp(
    `location = ${path.replace('.', '\\.')} \\{([\\s\\S]*?)\\n    \\}`,
  ).exec(nginx)
  assert.ok(block, `nginx.conf has no exact-match location for ${path}`)
  // Anchored to a `return` at the start of its own line: `/robots.txt` also carries a CONDITIONAL
  // `if ($cf_env) { return 200 '…'; }` above it, and a regex that took the first match would read
  // the non-mainnet body and report the mainnet one as drifted.
  const body = /\n {8}return 200 '([\s\S]*?)';/.exec(block[1] ?? '')
  assert.ok(body, `the ${path} location does not return an unconditional literal body`)
  return body[1] ?? ''
}

/** The address a route canonicalises to, in the form nginx composes it. */
function address(path: string): string {
  // The index is bare `$scheme://$host`, never `$scheme://$host/`. One page must not acquire two
  // addresses and split its own indexing between them — the same normalisation `normalisePath` in
  // @cloudsforge/ui/seo applies to the canonical link this app writes at runtime.
  return path === '/' ? '$scheme://$host' : `$scheme://$host${path}`
}

describe('the sitemap nginx serves', () => {
  it('names no hostname — every address is composed from $host', () => {
    /*
     * THE ASSERTION THAT KEEPS THE ARTEFACT ENVIRONMENT-FREE, and the reason this arrangement is
     * allowed at all. A single literal apex here would make the image wrong on a preview
     * deployment and on testnet, silently, in the one document a crawler treats as authoritative.
     */
    const xml = servedBody('/sitemap.xml')
    assert.ok(!xml.includes(APEX), 'the sitemap names the production apex')
    assert.ok(!xml.includes('localhost'), 'the sitemap names localhost')
    const locs = [...xml.matchAll(/<loc>([^<]*)<\/loc>/g)].map((m) => m[1] ?? '')
    assert.ok(locs.length > 0, 'the sitemap has no <loc> at all')
    for (const loc of locs) {
      assert.match(loc, /^\$scheme:\/\/\$host/, `a <loc> is not composed from $host: ${loc}`)
    }
  })

  it('composes no sibling surface, because this host is not the apex', () => {
    // `$scheme://foresight.$host` on THIS surface is `foresight.market.<apex>`: the two-label shape
    // that resolves nowhere and fails the edge's one-label wildcard certificate. The estate
    // sitemap is `site`'s, and this assertion is what stops somebody copying it here.
    const xml = servedBody('/sitemap.xml')
    assert.ok(
      !/<loc>\$scheme:\/\/[a-z-]+\.\$host/.test(xml),
      'the sitemap prefixes a subdomain onto a host that already has one',
    )
  })

  it('lists every public route, and nothing that is gated or unbounded', () => {
    const xml = servedBody('/sitemap.xml')
    const locs = new Set([...xml.matchAll(/<loc>([^<]*)<\/loc>/g)].map((m) => m[1] ?? ''))

    for (const path of SITEMAP_PATHS) {
      assert.ok(locs.has(address(path)), `${path} is missing from the sitemap`)
    }
    // The other direction, which is the one that goes wrong quietly: an entry left behind after a
    // route was gated advertises a page that answers a crawler with a redirect to sign in.
    assert.equal(
      locs.size,
      SITEMAP_PATHS.length,
      `the sitemap lists ${locs.size} addresses; the route table declares ${SITEMAP_PATHS.length}`,
    )
    for (const route of ROUTES) {
      if (route.indexable) continue
      assert.ok(
        !locs.has(address(`/${route.path}`)),
        `/${route.path} is not indexable and must not be advertised`,
      )
    }
  })

  it('is the three routes a signed-out reader can actually open', () => {
    // Named rather than only derived, so that flipping `indexable` on a gated route fails here as
    // well as passing the derivation above. /sell and /orders are behind ProtectedRoute;
    // /listings/<uuid> and /collections/<uuid> are unbounded.
    assert.deepEqual([...SITEMAP_PATHS], ['/', '/collections', '/fees'])
  })

  it('is served as XML, because a sitemap sent as text/html is a sitemap nobody reads', () => {
    // `types { }` as well as `default_type`: without emptying the table for this location, nginx
    // maps the `.xml` in the URI to `text/xml` from its own mime types and `default_type` never
    // applies — a declaration that reads as a decision and is not one.
    assert.match(
      nginx,
      /location = \/sitemap\.xml \{[\s\S]*?types \{ \}[\s\S]*?default_type application\/xml;/,
    )
  })

  it('restates the security headers, because add_header does not accumulate', () => {
    // A location declaring ANY add_header inherits NONE from the server level. Both of the blocks
    // added here declare Cache-Control, so both had to restate the other three or ship without
    // them — the exact defect `location /assets/` records having shipped once already.
    for (const path of ['/sitemap.xml', '/robots.txt']) {
      const block = new RegExp(`location = ${path.replace('.', '\\.')} \\{([\\s\\S]*?)\\n    \\}`)
        .exec(nginx)?.[1]
      assert.ok(block, `no exact-match location for ${path}`)
      for (const header of ['X-Content-Type-Options', 'X-Frame-Options', 'Referrer-Policy']) {
        assert.match(block, new RegExp(header), `${path} is served without ${header}`)
      }
    }
  })
})

describe('an environment that is not mainnet', () => {
  /**
   * The `map` that decides it, and the alternation of labels inside it.
   *
   * A testnet estate carries test EMBER, a faucet and deliberately broken states. Every page of it
   * competing with the real one in a search index is a support problem before it is an SEO problem
   * — so a non-mainnet hostname is not indexed at all, rather than indexed carefully.
   */
  function alternation(): string[] {
    const map = /map \$host \$cf_env \{[\s\S]*?~\^[^\n]*?\(\?:([^)]*)\)\\\./.exec(nginx)
    assert.ok(map, 'the $cf_env map is missing from nginx.conf')
    return (map[1] ?? '').split('|')
  }

  it('recognises exactly the labels the registry reserves', () => {
    /*
     * ENV_LABELS is the estate's single list — `deploy/scripts/check-apex-prefix.py` reads the same
     * export. An alternation here that had drifted from it would either miss an environment (and
     * index it) or refuse a surface (and de-index a real one), and both fail silently.
     */
    assert.deepEqual(alternation().sort(), [...ENV_LABELS].sort())
  })

  it('refuses every crawler and serves no sitemap', () => {
    // Both halves matter and neither is sufficient: robots.txt stops the fetch, the 404 stops the
    // document being there to fetch, and a page that is only disallowed can still be indexed from
    // an inbound link.
    assert.match(nginx, /if \(\$cf_env\) \{ return 200 'User-agent: \*\\nDisallow: \/\\n'; \}/)
    assert.match(nginx, /location = \/sitemap\.xml \{[\s\S]*?if \(\$cf_env\) \{ return 404; \}/)
  })

  it('matches a suffixed subdomain as well as a bare environment apex', () => {
    // The environment is a SUFFIX on the first label now (`market-testnet.`) and was an apex prefix
    // (`testnet.`) before. Both shapes still resolve — surfaces.ts keeps the old one deliberately —
    // so the pattern has to catch both, and on THIS surface the suffixed one is the shape that
    // actually occurs, because `market` is a subdomain and cannot also be an apex label.
    const map = /map \$host \$cf_env \{[\s\S]*?\n\}/.exec(nginx)
    assert.ok(map, 'the $cf_env map is missing')
    assert.match(map[0], /\(\?:\[\^\.\]\+-\)\?/, 'the map does not allow a suffixed subdomain')
  })
})

describe('robots.txt', () => {
  it('is exactly what the design system generates', () => {
    // Compared with its trailing newline intact: robots.txt is a line-oriented format, and a parser
    // that reads the last line only when it is terminated silently loses the Sitemap directive.
    assert.equal(
      servedBody('/robots.txt'),
      robotsTxt({ indexable: true, sitemapUrl: '$scheme://$host/sitemap.xml' }),
    )
  })

  it('points at the sitemap with an absolute address, composed rather than typed', () => {
    // A relative `Sitemap:` line is invalid per the standard and is ignored; a literal one bakes in
    // a hostname. `$scheme://$host` is the only form that is both valid and environment-free.
    assert.match(servedBody('/robots.txt'), /^Sitemap: \$scheme:\/\/\$host\/sitemap\.xml$/m)
  })

  it('is not a static file, because an exact-match location would have shadowed it', () => {
    /*
     * `location = /robots.txt` wins over the `location /` prefix that serves the static tree, so a
     * `public/robots.txt` would be in the repository, deployed, and unreachable — the worst of the
     * three states, because the next reader edits it and nothing happens.
     */
    let present = true
    try {
      readFileSync(new URL('../public/robots.txt', import.meta.url))
    } catch {
      present = false
    }
    assert.equal(present, false, 'public/robots.txt is back, and nginx will never serve it')
  })
})
